name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make git

      - name: Setup Google Test
        run: |
          mkdir -p external
          cd external
          git clone https://github.com/google/googletest.git

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Run integration tests
        run: |
          cd build
          ./runIntegrationTests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: build/

      - name: Create deployment directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deployment/directory

      - name: Create executable
        run: |
          cp build/TicTacToe $GITHUB_WORKSPACE/deployment/directory/TicTacToe

      - name: Run the executable
        run: |
          $GITHUB_WORKSPACE/deployment/directory/TicTacToe
